FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8005
CMD ["gunicorn", "--bind", "0.0.0.0:8005", "recommendation_project.wsgi:application"]
