# Generated by Django 5.2.4 on 2026-03-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('access_approved', 'Access Approved'), ('access_denied', 'Access Denied'), ('payment_confirmed', 'Payment Confirmed'), ('new_content', 'New Content'), ('new_review', 'New Review'), ('review_liked', 'Review Liked'), ('recommendation', 'Recommendation'), ('watchlist', 'Watchlist'), ('welcome', 'Welcome'), ('system', 'System'), ('info', 'Info')], max_length=30),
        ),
    ]
