# Generated by Django 5.2.4 on 2026-03-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Smaller preview image for cards', null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='thumbnail_url',
            field=models.URLField(blank=True, default='', help_text='External thumbnail URL'),
        ),
    ]
