# Generated by Django 5.2.4 on 2026-03-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='payment_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Awaiting Payment'), ('completed', 'Payment Completed'), ('failed', 'Payment Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='user_email',
            field=models.EmailField(default='', max_length=255),
        ),
    ]
