# Generated by Django 5.2.4 on 2026-03-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_accessrequest_email_sent_accessrequest_payment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_code', models.CharField(max_length=100, unique=True)),
                ('movie_id', models.IntegerField(db_index=True)),
                ('movie_title', models.CharField(default='', max_length=500)),
                ('user_id', models.IntegerField(db_index=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movie_hashes',
                'ordering': ['-created_at'],
            },
        ),
    ]
