# Generated by Django 5.2.4 on 2026-03-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlickUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('favorite_genre', models.CharField(blank=True, default='', max_length=100)),
                ('total_watch_time', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'flick_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenreStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('genre', models.CharField(max_length=100)),
                ('watch_count', models.IntegerField(default=0)),
                ('total_minutes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'genre_stats',
                'ordering': ['-watch_count'],
                'unique_together': {('user_id', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('movie_id', models.IntegerField(db_index=True)),
                ('movie_title', models.CharField(default='', max_length=500)),
                ('movie_poster', models.URLField(blank=True, default='')),
                ('progress', models.FloatField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('last_position', models.IntegerField(default=0)),
                ('watched_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'watch_history',
                'ordering': ['-watched_at'],
                'unique_together': {('user_id', 'movie_id')},
            },
        ),
    ]
