# Generated by Django 5.2.4 on 2026-03-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_flickuser_avatar_flickuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='flickuser',
            name='has_super_access',
            field=models.BooleanField(default=False),
        ),
    ]
