# Generated by Django 5.2.4 on 2026-03-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_flickuser_has_super_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('movie_id', models.IntegerField(db_index=True)),
                ('movie_title', models.CharField(default='', max_length=500)),
                ('movie_slug', models.SlugField(default='', max_length=500)),
                ('movie_poster', models.URLField(blank=True, default='')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_watchlist',
                'ordering': ['-added_at'],
                'unique_together': {('user_id', 'movie_id')},
            },
        ),
    ]
