# Generated by Django 5.2.4 on 2026-03-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('recommendation_type', models.CharField(choices=[('personalized', 'Personalized'), ('similar', 'Similar'), ('collaborative', 'Collaborative'), ('trending', 'Trending')], max_length=20)),
                ('movie_ids', models.TextField(default='[]')),
                ('scores', models.TextField(default='[]')),
                ('source_movie_id', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cached_recommendations',
            },
        ),
        migrations.CreateModel(
            name='MovieFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('genres', models.TextField(default='[]')),
                ('tags', models.TextField(default='[]')),
                ('director', models.CharField(blank=True, default='', max_length=255)),
                ('year', models.IntegerField(default=2024)),
                ('rating', models.FloatField(default=0.0)),
                ('view_count', models.IntegerField(default=0)),
                ('trending_score', models.FloatField(default=0.0)),
                ('feature_vector', models.TextField(default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'movie_features',
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('movie_id', models.IntegerField(db_index=True)),
                ('interaction_type', models.CharField(max_length=20)),
                ('score', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_interactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
